name: kitepay_app_2026
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.1
  flutter_dotenv: ^6.0.1

  # --- ADD THIS LINE ---
  http: ^1.2.1
  
  # --- TURNKEY & CRYPTO ---
  turnkey_sdk_flutter: ^1.2.1
  turnkey_api_key_stamper: ^0.2.1
  web3dart: ^2.7.3 

  # --- KITE PAY ---
  kitepay_sdk:
    path: ./kitepay_sdk 

  # --- UI & UTILS ---
  flutter_html: ^3.0.0
  flutter_widget_from_html: ^0.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/KitePay.jpg